import { Member } from '@/types/member'

export const mockMembers: Member[] = [
  {
    id: '1',
    user_id: 'github-001',
    name_ko: '김오픈',
    name_en: 'Open Kim',
    company: 'Samsung Electronics',
    role: 'Open Source Program Manager',
    bio: '오픈소스 컴플라이언스 10년 경력. SPDX 한국 대표.',
    category: '기업',
    email: 'open.kim@example.com',
    email_public: false,
    phone_public: false,
    linkedin: 'https://linkedin.com/in/openkim',
    github: 'openkim',
    discord: 'openkim#1234',
    blog: 'https://openkim.dev',
    avatar_url: undefined,
    approved: true,
    created_at: '2024-01-15T09:00:00Z',
    updated_at: '2024-01-15T09:00:00Z',
  },
  {
    id: '2',
    user_id: 'github-002',
    name_ko: '이체인',
    name_en: 'Chain Lee',
    company: 'LG Electronics',
    role: 'Software Architect',
    bio: 'OpenChain 인증 전담 팀 리드. FOSS 정책 수립 경험.',
    category: '기업',
    email: 'chain.lee@example.com',
    email_public: true,
    phone_public: false,
    linkedin: 'https://linkedin.com/in/chainlee',
    github: 'chainlee',
    discord: undefined,
    blog: undefined,
    avatar_url: undefined,
    approved: true,
    created_at: '2024-01-20T10:00:00Z',
    updated_at: '2024-01-20T10:00:00Z',
  },
  {
    id: '3',
    user_id: 'github-003',
    name_ko: '박소스',
    name_en: 'Source Park',
    company: 'ETRI',
    role: '선임연구원',
    bio: '공개SW R&D 및 라이선스 연구. OpenChain KWG 운영진.',
    category: '연구/공공',
    email: 'source.park@example.com',
    email_public: false,
    phone_public: false,
    linkedin: undefined,
    github: 'sourcepark',
    discord: 'sourcepark#5678',
    blog: 'https://etri.re.kr/blog',
    avatar_url: undefined,
    approved: true,
    created_at: '2024-02-01T11:00:00Z',
    updated_at: '2024-02-01T11:00:00Z',
  },
  {
    id: '4',
    user_id: 'github-004',
    name_ko: '최컴플',
    name_en: 'Compl Choi',
    company: 'Kakao',
    role: 'Legal Counsel',
    bio: '오픈소스 법률 검토 및 컴플라이언스 정책 수립.',
    category: '기업',
    email: 'compl.choi@example.com',
    email_public: false,
    phone_public: false,
    linkedin: 'https://linkedin.com/in/complchoi',
    github: undefined,
    discord: undefined,
    blog: undefined,
    avatar_url: undefined,
    approved: true,
    created_at: '2024-02-10T13:00:00Z',
    updated_at: '2024-02-10T13:00:00Z',
  },
  {
    id: '5',
    user_id: 'github-005',
    name_ko: '정스타트',
    name_en: 'Start Jung',
    company: 'OSSLab Inc.',
    role: 'CEO',
    bio: '오픈소스 컨설팅 스타트업 창업자. 중소기업 컴플라이언스 지원.',
    category: '기업',
    email: 'start.jung@example.com',
    email_public: true,
    phone_public: false,
    linkedin: 'https://linkedin.com/in/startjung',
    github: 'startjung',
    discord: 'startjung#9999',
    blog: 'https://osslab.io/blog',
    avatar_url: undefined,
    approved: true,
    created_at: '2024-03-01T09:30:00Z',
    updated_at: '2024-03-01T09:30:00Z',
  },
  {
    id: '6',
    user_id: 'github-006',
    name_ko: '한미들',
    name_en: 'Middle Han',
    company: 'Hyundai Mobis',
    role: 'Software Safety Engineer',
    bio: '자동차 소프트웨어 공급망 오픈소스 컴플라이언스.',
    category: '기업',
    email: 'middle.han@example.com',
    email_public: false,
    phone_public: false,
    linkedin: 'https://linkedin.com/in/middlehan',
    github: 'middlehan',
    discord: undefined,
    blog: undefined,
    avatar_url: undefined,
    approved: true,
    created_at: '2024-03-15T14:00:00Z',
    updated_at: '2024-03-15T14:00:00Z',
  },
]

export const CATEGORIES = ['기업', '연구/공공', '학계'] as const
